name: foundit
description: A new Flutter project.


publish_to: 'none' 


version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"


dependencies:
  flutter:
    sdk: flutter



  cupertino_icons: ^1.0.2
  introduction_screen: ^3.0.0
  image_picker: ^0.8.5+3
  firebase_auth: ^3.3.19
  flutter_map: ^1.0.0
  http: ^0.13.4
  latlong2: ^0.8.1
  dart_date: ^1.1.1
  cloud_firestore: ^3.4.4
  firebase_core: ^1.20.1
  firebase_storage: ^10.3.5
  firebase_messaging: ^12.0.2
  permission_handler: ^10.0.0
  intl: ^0.17.0
  cached_network_image: ^3.2.1
  sizer: ^2.0.15
  shared_preferences: ^2.0.15
  flutter_launcher_icons: ^0.10.0
  email_validator: ^2.1.17
  flutter_native_splash: ^2.2.9

flutter_icons:
  android: "launcher_icon"
  remove_alpha_ios: true
  ios: true
  image_path: "assets/images/appsplash.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
  adaptive_icon_background: "assets/images/appsplash.png"
  adaptive_icon_foreground: "assets/images/appsplashscreen.png"

flutter_native_splash:

    android: true
    ios: true
    web: true

    background_image: "assets/images/appsplashscreen.png"
    #image: assets/images/appsplashdark.png

    android_gravity: center
    ios_content_mode: center
    web_image_model: center

    fullscreen: true

    android_12:
    # The image parameter sets the splash screen icon image.  If this parameter is not specified,
    # the app's launcher icon will be used instead.
    # Please note that the splash screen will be clipped to a circle on the center of the screen.
    # App icon with an icon background: This should be 960×960 pixels, and fit within a circle
    # 640 pixels in diameter.
    # App icon without an icon background: This should be 1152×1152 pixels, and fit within a circle
    # 768 pixels in diameter.
    image: assets/images/founditicon.png

    # App icon background color.
    icon_background_color: "#FFFFFF"

    # The image_dark parameter and icon_background_color_dark set the image and icon background
    # color when the device is in dark mode. If they are not specified, the app will use the
    # parameters from above.
    image_dark: assets/images/founditicon.png
    icon_background_color_dark: "#FFFFFF"

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^1.0.0


flutter:


  uses-material-design: true

  
  assets:
    - assets/images/


  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat-ExtraLightItalic.ttf
        - asset: assets/fonts/Montserrat-BoldItalic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
